[test-groups]
uv = { max-threads = 1}

# On Windows, concurrent uv runs may fail by `Access Denied` errors
# due to concurrent uv cache writes.
# Configure these tests to run sequentially.
[[profile.default.overrides]]
filter = 'test(run_basic) | test(local_need_install)'
platform = 'cfg(windows)'
test-group = 'uv'
